name: flutter_amazon_adm
description: A Flutter plugin for Amazon Device Messaging (ADM) push notifications
version: 0.0.1
homepage: https://github.com/osmely/flutter_amazon_adm

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.kinesis.flutter_amazon_adm
        pluginClass: FlutterAmazonAdmPlugin
